import Head from 'next/head'
import Link from 'next/link'
import Image from "next/image";
import React from "react";
import {useSelector} from "react-redux";

export default function Home() {
    const userList = useSelector(state => state.users.users)

    console.log(userList)

    return (
        <div className="flex h-screen items-center  justify-center">
            <Head>
                <title>JMail</title>
                <meta name="description" content="Generated by create next app"/>
            </Head>
            <div className="w-1/3 border-2 flex flex-col items-center pt-5 pb-24 rounded-md" style={{minWidth:'300px'}}>
                <div>
                    <Image
                        priority
                        src="/images/google.png"
                        height={90}
                        width={90}
                        alt={`google-logo`}
                    />
                </div>
                <div className="text-2xl mb-5">계정 선택</div>
                <ul className="w-full">
                    {userList && userList.map(({id, name, email, nickName, color}) =>
                        <Link key={id}
                              href={{
                                  pathname: '/login',
                                  query: {
                                      userId: id,
                                      name,
                                      email,
                                      nickName,
                                      color
                                  }
                              }}>
                            <li className="flex items-center cursor-pointer border-b py-3 mx-5">
                                <div
                                    style={{backgroundColor: `${color}`}}
                                    className={`rounded-full w-7 h-7 flex items-center justify-center text-xs font-semiBold text-white mr-5`}>
                                    {nickName}</div>
                                <div>
                                    <div>{name}</div>
                                    <div className="text-gray-500 text-sm">{email}</div>
                                </div>
                            </li>
                        </Link>
                    )}

                </ul>
            </div>
        </div>
    )
}
