import Head from 'next/head'
import Link from 'next/link'
import Image from "next/image";
import React from "react";
import {useSelector} from "react-redux";

export default function Home() {
    const userList = useSelector(state=>state.users.users)

    return (
        <div className="flex h-screen items-center justify-center">
            <Head>
                <title>JMail</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <div className="w-600px border-2 flex flex-col items-center py-5">
                <div>
                    <Image
                        priority
                        src="/images/google.png"
                        height={100}
                        width={100}
                        alt={`google-logo`}
                    />
                </div>
                <div className="text-4xl mb-5">계정 선택</div>
                <ul className="pb-64">
                    {userList && userList.map(({id, name, email, nickName, color}) =>
                        <Link key={id}
                              href={{
                                  pathname: '/login',
                                  query: {
                                      userId: id,
                                      name,
                                      email,
                                      nickName,
                                      color
                                  }
                              }}>
                            <li className="flex items-center cursor-pointer border-b py-3 w-96">
                                <div
                                    className={`${color} rounded-full w-10 h-10 flex items-center justify-center text-l font-semiBold text-white mr-5`}>{nickName}</div>
                                <div>
                                    <div>{name}</div>
                                    <div>{email}</div>
                                </div>
                            </li>
                        </Link>
                    )}

                </ul>
            </div>
        </div>
    )
}
